from __future__ import annotations

from pathlib import Path


CHUNK_ATTEMPTS_MAX = 4
CHUNK_RETRY_BACKOFF_SECONDS = 1.5
CHUNK_RETRY_JITTER_SECONDS = 0.5
CHUNK_WORKERS_MAX = 10
ENVIRONMENT_BOMS = (
    (b'\xff\xfe\x00\x00', 'utf-32-le'),
    (b'\x00\x00\xfe\xff', 'utf-32-be'),
    (b'\xff\xfe', 'utf-16-le'),
    (b'\xfe\xff', 'utf-16-be'),
    (b'\xef\xbb\xbf', 'utf-8-sig'),
)
ENVIRONMENT_FILE_NAME = '.env'
KEY_ATTEMPTS_MAX = 10
OUTPUT_ATTEMPTS_MAX = 999
OUTPUT_MODE_BOTH = 'both'
OUTPUT_MODE_NOTES = 'notes'
OUTPUT_MODE_TRANSCRIPT = 'transcript'
OUTPUT_MODES = (OUTPUT_MODE_BOTH, OUTPUT_MODE_NOTES, OUTPUT_MODE_TRANSCRIPT)
POLISH_ATTEMPTS_MAX = 3
POLISH_CHARACTERS_MAX = 12000
POLISH_RETRY_BACKOFF_SECONDS = 2.0
POLISH_TIMEOUT_SECONDS = 180.0
POLISH_WORKERS_MAX = 4
SCRIPT_DIRECTORY = Path(__file__).resolve().parent
LOG_PATH = SCRIPT_DIRECTORY.parent / 'mimir.log'
SEARCH_CHUNKS_MAX = 50
SEARCH_QUERY_CHARACTERS_MAX = 2000
SEGMENT_LENGTH_SECONDS = 30
SUPPORTED_AUDIO_EXTENSIONS = ('mp3', 'wav', 'flac', 'mp4', 'mpeg', 'ogg', 'm4a', 'webm')
SUPPORTED_DOCUMENT_EXTENSIONS = ('docx', 'md', 'txt')
